[package]
name = "stripack-sys"
version = "0.1.0"
edition = "2024"
links = "stripack"
license = "MIT OR Apache-2.0"

[build-dependencies]
cc = "1"

[dev-dependencies]
rstest = "^0.26.1"
proptest = "^1.9.0"
test-strategy = "^0.4.4"
