name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check Formatting
        run: cargo fmt --check
      - name: Check Clippy
        run: cargo clippy -- -D warnings
      - name: Check Documentation
        run: cargo doc --no-deps

  test:
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86_64
            os: ubuntu-latest
            fortran: gfortran

          - name: macOS Apple Silicon
            os: macos-14
            fortran: gcc

          - name: Windows MinGW
            os: windows-latest
            fortran: mingw-w64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Fortran (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gfortran

      - name: Setup Fortran (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install gcc

      - name: Debug gfortran location (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          which gfortran
          ls -la /opt/homebrew/lib/ | grep gfortran || echo "not in /opt/homebrew/lib"
          ls -la /opt/homebrew/lib/gcc/*/ || echo "checking gcc subdirs"
          brew list gcc | grep gfortran || echo "checking brew list"

      - name: Setup Fortran (Wndows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo nextest run

      - name: Generate coverage
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

